### ISSUE TITLE
No oAuth2 Sign In Option

### ISSUE THREAD

**Issue by rbebout** [OfficeDev/Project-Power-BI-Templates#11]
When I try to connect my PWA source I type in the URL and 1 but on the user authentication page I am not given the option to choose oAuth2 for my login type. All I have is Anonymous, Windows, Basic, and Key. Any idea why I might be getting only those options?

**Comment by rbebout** [comment]
![No_oAuth2_SignInOption](https://user-images.githubusercontent.com/58477109/74053286-7cc7f000-49a9-11ea-8228-dfa23470ad2d.PNG)

Here is an example of what I am seeing when I try to log in. Please help

**Comment by mchaouki2** [comment]
Same here no Organizational account option on PowerBI Online like the desktop version does.
This results in data refresh failures. Any suggestions?

**Comment by sadanapriyanka** [comment]
Hi @rbebout 

Could you please help me with this:
1. Which template file are you using?
2. Are you using the Power Bi Desktop Client?

Regards

**Comment by rbebout** [comment]
Hello @sadanapriyanka , 

I have tried both the online version and the desktop client. Neither have allowed me to use oAuth2. The picture from earlier is the Online version and the picture attached is from the desktop. I dont have the option to choose the oAuth2 method for either. 

I am using the "Microsoft Project Online Power BI Content Pack.pbit" file from the package. 

Also, I have admin level permissions to the share point PWA site that I am connecting to. 

Thank you so much for your response. Please let me know if you need any other screenshots to troubleshoot what might be going on. 

Best,
Rob


![OAuth2_DesktopError](https://user-images.githubusercontent.com/58477109/74338500-5242b200-4d70-11ea-963e-f6d85dcfb103.PNG)

**Comment by sadanapriyanka** [comment]
Hi @rbebout 

Can you try with your organizational account here?

**Comment by sadanapriyanka** [comment]
Hi @rbebout 

Were you able to solve the issue?
