### ISSUE TITLE
Unable to schedule refresh: "Query contains unsupported function. Function name: OData.Feed"

### ISSUE THREAD

**Issue by jdshkolnik** [OfficeDev/Project-Power-BI-Templates#12]
> You can't schedule refresh for this dataset because the following data sources currently don't support refresh:
> Data source for "Bookable Resources"
> Data source for Projects
> Data source for "Project Tasks"
> Data source for "Project Team"
> Data source for "Resource Assignments"
> Data source for "Task Team"
> Discover Data Sources
> Query contains unsupported function. Function name: OData.Feed

I found [this discussion](https://community.powerbi.com/t5/Service/PBI-app-cannot-load-odata-feed-with-M-functions-in-the-URL/td-p/743164) which might help understand how to resolve it.

**Comment by sadanapriyanka** [comment]
Hi @jdshkolnik 

Thanks for reporting it. We have uploaded the Project for the Web Report to the repo.

Meanwhile we are working on the issue here. Thank you.

Kind Regards

**Comment by donalmc** [comment]
Removing the PWA appends fixes the issue

**Comment by donalmc** [comment]
Actually, if you don't need to report on PWA, there is a P4W pbit (which works totally fine) - which seems obvious now, but wasn't to me initially!
