### ISSUE TITLE
Project Online Custom Fields 

### ISSUE THREAD

**Issue by wiredawghall** [OfficeDev/Project-Power-BI-Templates#14]
I am trying to use Power BI for my dashboard reporting but when I try to find my custom fields that were set up, such as Project Status, I can not find the field to select for the report. All of the other fields seem to be present with the most up to date data.

**Comment by sadanapriyanka** [comment]
Hi @wiredawghall, could you please let us know if your using Project for the Web or Project online?

The custom fields in Project for the Web are not available for reporting.

**Comment by pscheiman** [comment]
When will reporting on Project for the web custom fields be available?

**Comment by ioannis-ts** [comment]
> Hi @wiredawghall, could you please let us know if your using Project for the Web or Project online?
> 
> _The custom fields in Project for the Web are not available for reporting_.

This is a huge caveat since a lot of fields are missing from the Project for the Web, such as costs, and we need to add them manually.
Can we retrieve them, import them somehow with a query?

**Comment by BeReasonable** [comment]
Hello everyone, can you add feedback about local custom fields in our [User Voice site](https://microsoftproject.uservoice.com/forums/914203-project-for-the-web)? 

For example, I'd love to learn more about your needs around reporting of local custom fields, or whether you're looking for something akin to enterprise custom fields. 

Thanks!

**Comment by ioannis-ts** [comment]
> Hello everyone, can you add feedback about local custom fields in our [User Voice site](https://microsoftproject.uservoice.com/forums/914203-project-for-the-web)?
> 
> For example, I'd love to learn more about your needs around reporting of local custom fields, or whether you're looking for something akin to enterprise custom fields.
> 
> Thanks!

Hello BeReasonble,

There are 2 submissions for both additional Enterprise fields and for the custom fields to be able to show in PowerBI.
please find below the submissions 
https://microsoftproject.uservoice.com/forums/914203-project-for-the-web/suggestions/40321114-enterprise-custom-fields-for-project-for-the-web-p
https://microsoftproject.uservoice.com/forums/914203-project-for-the-web/suggestions/41532838-custom-field-visibility-within-power-bi-or-power-a

**Comment by jairmarinjr** [comment]
Hi there!

Any updates on this matter? I need to link the Enterprise custom field on Project Web App and the report on Power BI.
