### ISSUE TITLE
Task URL

### ISSUE THREAD

**Issue by TheThettinger** [OfficeDev/Project-Power-BI-Templates#16]
Anyway to pull the Task link to create a Task URL?

**Comment by sadanapriyanka** [comment]
@TheThettinger Please follow these steps to add Task URL.

1. Open transform data in Power Bi Desktop. 
2. Select the "Project Tasks" table.
3. Add a new custom column. In the editor window, enter: "https://project.microsoft.com/?org="& Text.Middle(#"Dataverse URL",8)& "#/taskboard?projectId="&[Project ID]& "&taskId="&Text.Upper([Task ID])

Let us know if this helps.
