### ISSUE TITLE
Roadmap report pages are not working

### ISSUE THREAD

**Issue by ferrety2006** [OfficeDev/Project-Power-BI-Templates#9]
Not sure what all tables were supposed to come in, but the Roadmap reports (Roadmap Key Dates & Roadmap Details) are coming up with errors. The fields the visuals are looking for are not present. Within the fields list, there is not a "Roadmap" table. Tried with a normal user account in our tenant for the data source credentials and also tried global admin credentials; same results.

Edited the query and found that the Roadmap tables were not enabled for load. Enabled all roadmap tables, loaded, auto-detected relationships, edited some relationships, and now we seem to be working ok.

**Comment by halcyondude** [comment]
+1, seeing same issue

**Comment by mchaouki2** [comment]
+1 same here

**Comment by sadanapriyanka** [comment]
Hi, 

Roadmap queries and tables have been disabled and will be released in near future.

**Comment by JSeluga** [comment]
When are they going to be released
